### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ramirezg** [18F/analytics-proxy-nodejs#1]
- [x] rearrange project structure to fit NodeJS best practices
- [x] load/cache GA data into database properly. Probably fix a line [here](https://github.com/18F/analytics-proxy-nodejs/blob/master/analytics/get_analytics.js)
- [ ] better documentation 
- [ ] create a way of loading data initially
- [ ] create a way to loop through both specific and general queries when needed.

**Comment by konklone** [comment]
Closing this, to be re-opened or adapted for a phase 2.
